## 分类

鸢尾花

气候不同造就性状不同，统计了鸢尾花的关键特征数据：
花萼长度，花萼宽度，花瓣长度，花瓣宽度。

植物家划分为：
- setosa  山鸢尾
- versicolor 杂色鸢尾
- virginica 弗吉尼亚鸢尾

鸢尾花数据集中每个样本包含4个特征（花萼长度，花萼宽度，花瓣长度，花瓣宽度），用于对鸢尾花进行分类


KNN 算法

加载数据

数据预处理，拆分

声明算法，给定超参数 k

训练算法，拟合数据，归纳规律

算法应用，样本预测

#### 数据加载

In [1]:
from sklearn import datasets  #示例数据集
from sklearn.neighbors import KNeighborsClassifier  #分类

In [2]:
X,y = datasets.load_iris(return_X_y=True)
display(X,y)

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
X.shape

(150, 4)

#### 数据拆分

In [9]:
# train 训练数据 test 测试数据
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,#要拆分数据
                 test_size=0.2,#拆分比例，测试数据20%
                 random_state=1024)#固定了随机状态
display(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(120, 4)

(30, 4)

(120,)

(30,)

#### 算法建模

In [13]:
model=KNeighborsClassifier(n_neighbors=5)  #给定5个邻居

In [14]:
model.fit(X_train,y_train) #建模，拟合，训练

KNeighborsClassifier()

#### 算法预测

In [16]:
y_=model.predict(X_test)
y_ 

array([1, 0, 2, 2, 0, 0, 1, 2, 1, 0, 0, 0, 1, 2, 2, 0, 1, 0, 2, 0, 2, 0,
       1, 0, 2, 1, 2, 2, 2, 2])

In [18]:
print('保留测试数据，真实值：',y_test)

保留测试数据，真实值： [1 0 2 2 0 0 1 2 1 0 0 0 1 2 1 0 1 0 2 0 2 0 1 0 2 1 2 2 2 2]


In [19]:
# 准确率计算方法1
(y_==y_test).mean()

0.9666666666666667

In [20]:
#准确率计算方法2
model.score(X_test,y_test)

0.9666666666666667

过拟合：小明平常学习好，但是一考试，都是新题，不会举一反三。

## KNN 交叉验证-算法调优

In [21]:
## 加载数据 拆分\
import numpy as np
from sklearn import datasets  #示例数据集
from sklearn.neighbors import KNeighborsClassifier  #分类

In [22]:
#X 表示数据，y目标值
X,y = datasets.load_iris(return_X_y=True)
display(X,y)

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [25]:
# train 训练数据 test 测试数据
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

X_train,X_test,y_train,y_test=train_test_split(X,y,#要拆分数据
                 test_size=0.2,#拆分比例，测试数据20%
                 random_state=42)#固定了随机状态
display(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(120, 4)

(30, 4)

(120,)

(30,)

In [26]:
#### 超参数-交叉验证筛选
params_k = np.arange(1,31)

scores = []
for k in params_k:
    knn=KNeighborsClassifier(n_neighbors=k)
    score=cross_val_score(knn,X_train,y_train,cv=5,scoring='accuracy').mean()
    scores.append(score)
display(scores)


[0.95,
 0.95,
 0.9583333333333334,
 0.95,
 0.9416666666666667,
 0.9416666666666667,
 0.9416666666666667,
 0.9333333333333333,
 0.9333333333333333,
 0.9333333333333333,
 0.95,
 0.9416666666666667,
 0.9416666666666667,
 0.9416666666666667,
 0.9416666666666667,
 0.9416666666666667,
 0.9416666666666667,
 0.9416666666666667,
 0.9416666666666667,
 0.9416666666666667,
 0.95,
 0.925,
 0.9333333333333333,
 0.9166666666666667,
 0.9416666666666667,
 0.9333333333333333,
 0.9416666666666667,
 0.9333333333333333,
 0.9333333333333333,
 0.9166666666666667]

In [29]:
k_best=np.argmax(scores)+1
print('得分最高的超参数K值是',k_best)

得分最高的超参数K值是 3


#### 选择最佳超参数建模和预测

In [30]:
estmator = KNeighborsClassifier(n_neighbors=k_best)
estmator.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [31]:
y_=estmator.predict(X_test)

In [32]:
print(y_)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [33]:
print(y_test)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [34]:
estmator.score(X_test,y_test)

1.0